version: '3.1'
services:
    # DATABASES
    db-dev:
        container_name: db
        image: postgres:14-alpine
        restart: always
        ports:
            - "5435:5432"
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: dev
        volumes:
            - ./database/postgres/data-dev:/var/lib/postgresql/data